name: deploy website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: website-473318
        export_default_credentials: true
    
    - name: Deploy to Cloud Storage
      run: |
        gsutil -m rsync -r -d . gs://andrew-killion-personal-website
        gsutil web set -m index.html -e 404.html gs://andrew-killion-personal-website