name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: website-473318 
    
    - name: Deploy to Cloud Storage
      run: |
        gsutil -m rsync -r -d . gs://andrewkillion.com
        gsutil web set -m index.html -e 404.html gs://andrewkillion.com